name: Generate and Send Omnivook

on:
  schedule:
    # Schedule the workflow to run every day at 17:30 Argentina time (20:30 UTC)
    - cron: '30 20 * * *'
  workflow_dispatch:
    inputs:
      since:
        description: 'Start date to filter articles (format YYYY-MM-DD)'
        required: false
      label:
        description: 'Label to filter'
        required: false
        default: k 
      archive:
        description: 'Archive exported articles'
        type: boolean
        default: true # default is true; can be set to false

jobs:
  generate_and_send_ebook:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Generate eBook
      env:
        OMNIVORE_TOKEN: ${{ secrets.OMNIVORE_TOKEN }}
      run: |
        SINCE_DATE="${{ inputs.since }}"
        if [ -z "$SINCE_DATE" ]; then
          SINCE_DATE=$(date -d '1 day ago' +%Y-%m-%d)
        fi
        
        ARCHIVE_FLAG=""
        if [ ${{ inputs.archive }} ]; then
          ARCHIVE_FLAG="--archive"
        fi
        
        python omnivook.py --label=${{ inputs.label }} --since $SINCE_DATE $ARCHIVE_FLAG
    
    - name: Send eBook via email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SERVER }} 
        subject: "Your Omnivook"
        body: "Attached is your new Omnivook eBook."
        to: ${{ secrets.MAIL_TO }}
        from: ${{ secrets.MAIL_FROM }}
        server_port: 465
        secure: true
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        attachments: _build/epub/omnivook.epub